[Sat May 06 23:20:34.557342 2023] [mpm_prefork:notice] [pid 687] AH00163: Apache/2.4.52 (Ubuntu) mod_wsgi/4.9.4 Python/3.9 mod_fcgid/2.3.9 configured -- resuming normal operations
[Sat May 06 23:20:34.559547 2023] [core:notice] [pid 687] AH00094: Command line: '/usr/sbin/apache2 -f /omd/sites/cmk/etc/apache/apache.conf'
[Mon May 08 12:02:38.406642 2023] [mpm_prefork:notice] [pid 132] AH00163: Apache/2.4.52 (Ubuntu) mod_wsgi/4.9.4 Python/3.9 mod_fcgid/2.3.9 configured -- resuming normal operations
[Mon May 08 12:02:38.409604 2023] [core:notice] [pid 132] AH00094: Command line: '/usr/sbin/apache2 -f /omd/sites/cmk/etc/apache/apache.conf'
[Thu May 11 12:05:39.646477 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120] mod_wsgi (pid=136): Exception occurred processing WSGI script '/omd/sites/cmk/share/check_mk/web/app/index.wsgi'.
[Thu May 11 12:05:40.398264 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120] Traceback (most recent call last):
[Thu May 11 12:05:40.402138 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/profiling.py", line 74, in __call__
[Thu May 11 12:05:40.412478 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     return app(environ, start_response)
[Thu May 11 12:05:40.413560 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/middleware.py", line 18, in __call__
[Thu May 11 12:05:40.415211 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     response = self.app(environ, start_response)
[Thu May 11 12:05:40.417078 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/middleware.py", line 32, in _add_apache_env
[Thu May 11 12:05:40.418858 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     return app(environ, start_response)
[Thu May 11 12:05:40.420458 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/routing.py", line 91, in router
[Thu May 11 12:05:40.421544 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     return endpoint(environ, start_response)
[Thu May 11 12:05:40.423587 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
[Thu May 11 12:05:40.425788 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     return self.app(environ, start_response)
[Thu May 11 12:05:40.430086 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/applications/checkmk.py", line 223, in __call__
[Thu May 11 12:05:40.431578 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     config_module.initialize()
[Thu May 11 12:05:40.433164 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 99, in initialize
[Thu May 11 12:05:40.434195 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     load_config()
[Thu May 11 12:05:40.471583 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 160, in load_config
[Thu May 11 12:05:40.473148 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     execute_post_config_load_hooks()
[Thu May 11 12:05:40.475575 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 191, in execute_post_config_load_hooks
[Thu May 11 12:05:40.477498 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     func()
[Thu May 11 12:05:40.480141 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/userdb.py", line 1336, in update_config_based_user_attributes
[Thu May 11 12:05:40.486178 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     cmk.gui.plugins.userdb.ldap_connector.register_user_attribute_sync_plugins()
[Thu May 11 12:05:40.489284 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/plugins/userdb/ldap_connector.py", line 1658, in register_user_attribute_sync_plugins
[Thu May 11 12:05:40.493639 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     "title": attr.valuespec().title(),
[Thu May 11 12:05:40.495401 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/plugins/userdb/user_attributes.py", line 174, in valuespec
[Thu May 11 12:05:40.496836 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     choices=theme_choices(),
[Thu May 11 12:05:40.503233 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/utils/theme.py", line 121, in theme_choices
[Thu May 11 12:05:40.504824 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     for base_dir in [Path(cmk.utils.paths.web_dir), cmk.utils.paths.local_web_dir]:
[Thu May 11 12:05:40.506206 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 1082, in __new__
[Thu May 11 12:05:40.508132 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     self = cls._from_parts(args, init=False)
[Thu May 11 12:05:40.511950 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 707, in _from_parts
[Thu May 11 12:05:40.514046 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     drv, root, parts = self._parse_args(args)
[Thu May 11 12:05:40.529718 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 700, in _parse_args
[Thu May 11 12:05:40.531740 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     return cls._flavour.parse_parts(parts)
[Thu May 11 12:05:40.533683 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 77, in parse_parts
[Thu May 11 12:05:40.539848 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     for x in reversed(rel.split(sep)):
[Thu May 11 12:05:40.540866 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]   File "/omd/sites/cmk/lib/python3/cmk/gui/utils/timeout_manager.py", line 37, in handle_request_timeout
[Thu May 11 12:05:40.542011 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120]     raise RequestTimeout(
[Thu May 11 12:05:40.543477 2023] [wsgi:error] [pid 136] [client 127.0.0.1:57120] cmk.gui.exceptions.RequestTimeout: Your request timed out after 110 seconds. This issue may be related to a local configuration problem or a request which works with a too large number of objects. But if you think this issue is a bug, please send a crash report.
[Thu May 11 19:47:41.445912 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694] mod_wsgi (pid=292): Exception occurred processing WSGI script '/omd/sites/cmk/share/check_mk/web/app/index.wsgi'.
[Thu May 11 19:47:41.768265 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694] Traceback (most recent call last):
[Thu May 11 19:47:41.773260 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/profiling.py", line 74, in __call__
[Thu May 11 19:47:41.775907 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     return app(environ, start_response)
[Thu May 11 19:47:41.777940 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/middleware.py", line 18, in __call__
[Thu May 11 19:47:41.780615 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     response = self.app(environ, start_response)
[Thu May 11 19:47:41.782153 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/middleware.py", line 32, in _add_apache_env
[Thu May 11 19:47:41.784393 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     return app(environ, start_response)
[Thu May 11 19:47:41.786566 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/routing.py", line 91, in router
[Thu May 11 19:47:41.797697 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     return endpoint(environ, start_response)
[Thu May 11 19:47:41.803449 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
[Thu May 11 19:47:41.808023 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     return self.app(environ, start_response)
[Thu May 11 19:47:41.810734 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/wsgi/applications/checkmk.py", line 223, in __call__
[Thu May 11 19:47:41.811716 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     config_module.initialize()
[Thu May 11 19:47:41.813862 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 99, in initialize
[Thu May 11 19:47:41.815981 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     load_config()
[Thu May 11 19:47:41.817765 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 160, in load_config
[Thu May 11 19:47:41.845581 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     execute_post_config_load_hooks()
[Thu May 11 19:47:41.873850 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/config.py", line 191, in execute_post_config_load_hooks
[Thu May 11 19:47:41.877018 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     func()
[Thu May 11 19:47:41.878298 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/userdb.py", line 1336, in update_config_based_user_attributes
[Thu May 11 19:47:41.884613 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     cmk.gui.plugins.userdb.ldap_connector.register_user_attribute_sync_plugins()
[Thu May 11 19:47:41.886711 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/plugins/userdb/ldap_connector.py", line 1659, in register_user_attribute_sync_plugins
[Thu May 11 19:47:41.890086 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     "help": attr.valuespec().help(),
[Thu May 11 19:47:41.893761 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/plugins/userdb/user_attributes.py", line 174, in valuespec
[Thu May 11 19:47:41.898167 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     choices=theme_choices(),
[Thu May 11 19:47:41.906469 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/utils/theme.py", line 129, in theme_choices
[Thu May 11 19:47:41.908389 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     for theme_dir in theme_base_dir.iterdir():
[Thu May 11 19:47:41.910178 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3.9/pathlib.py", line 1160, in iterdir
[Thu May 11 19:47:41.911149 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     for name in self._accessor.listdir(self):
[Thu May 11 19:47:41.913657 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]   File "/omd/sites/cmk/lib/python3/cmk/gui/utils/timeout_manager.py", line 37, in handle_request_timeout
[Thu May 11 19:47:41.931560 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694]     raise RequestTimeout(
[Thu May 11 19:47:41.954265 2023] [wsgi:error] [pid 292] [client 127.0.0.1:46694] cmk.gui.exceptions.RequestTimeout: Your request timed out after 110 seconds. This issue may be related to a local configuration problem or a request which works with a too large number of objects. But if you think this issue is a bug, please send a crash report.
